version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-5}
      - OPENAI_VERBOSITY=${OPENAI_VERBOSITY:-medium}
      - OPENAI_REASONING_EFFORT=${OPENAI_REASONING_EFFORT:-medium}
    volumes:
      - ./outputs:/app/outputs
    restart: unless-stopped

